---
name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build and Push (to Artifact Registry)"]
    types: [completed]
    branches: [week6-ga]

env:
  PROJECT_ID: heroic-throne-473405-m8
  CLUSTER: week6-cluster
  REGION: us-central1

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read image URI from file
        id: read
        run: |
          IMAGE=$(cat image-info.txt)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project $PROJECT_ID
          export GOOGLE_APPLICATION_CREDENTIALS="gcp-key.json"

      - name: Install GKE Auth Plugin (via APT)
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | \
            sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
            sudo tee /usr/share/keyrings/cloud.google.gpg >/dev/null
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      
      - name: Get GKE credentials
        env:
         GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
         USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          gcloud container clusters get-credentials $CLUSTER \
            --region $REGION \
            --project $PROJECT_ID

      - name: Deploy to GKE
        env:
         GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: |
          echo "Deploying image: $IMAGE"
          kubectl set image deployment/iris-fastapi iris-fastapi=$IMAGE --record || \
            kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/iris-fastapi --timeout=120s



