name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build and Push (to Artifact Registry)"]
    types:
      - completed
    branches:
      - week6-ga

env:
  PROJECT_ID: heroic-throne-473405-m8
  CLUSTER: week6-cluster
  CLUSTER_ZONE: us-central1-a

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-info

      - name: Read image URI
        id: read
        run: |
          IMAGE=$(cat image-info.txt)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ env.PROJECT_ID }}
          export GOOGLE_APPLICATION_CREDENTIALS="gcp-key.json"

      - name: Get credentials for GKE
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          echo "Deploying image: $IMAGE"
          kubectl set image deployment/iris-fastapi iris-fastapi=$IMAGE --record || kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl rollout status deployment/iris-fastapi --timeout=120s
